name: Hello world pipeline

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Latest Commit
      uses: actions/checkout@v2

    - name: Bump Version
      id: bump
      uses: nnichols/maven-version-bump-action@v3
      with:
        github-token: ${{ secrets.LOGGIN_TOKEN }}
        
    - name: Export version
      run: export VERSION=steps.bump.outputs.version
      
    - name: Build docker image
      run: docker build --build-arg="VERSION=$VERSION" -t github:$VERSION .

    - name: Test container
      run: docker run -it github:$VERSION

