name: Hello world pipeline

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Latest Commit
      uses: actions/checkout@v2

    - name: Bump Version
      id: bump
      uses: nnichols/maven-version-bump-action@v3
      with:
        github-token: ${{ secrets.LOGGIN_TOKEN }}
        
    - name: Build docker image
      run: docker build --build-arg=VERSION=${{ steps.bump.outputs.version }} -t github-ci:${{ steps.bump.outputs.version }} .

    - name: Test container
      run: docker run  github-ci:${{ steps.bump.outputs.version }}
      
    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Upload to dockerhub
      run: |
        docker tag github-ci:${{ steps.bump.outputs.version }} guyromano/github-ci:${{ steps.bump.outputs.version }}
        docker tag github-ci:${{ steps.bump.outputs.version }} guyromano/github-ci:latest
        docker push guyromano/github-ci:${{ steps.bump.outputs.version }}
        docker push guyromano/github-ci:latest



